### ISSUE TITLE
texto readme.me

### ISSUE THREAD

**Issue by Morkhusz** [PHPSP/phpsp-live#1]
Fala pessoal (ping @jpjoao @duodraco @joelmedeiros)!
Criei esta descrição para usarmos como base inicialmente. Sugestões de melhoria são muito bem-vindas.
A ideia é usar tanto aqui no README do repositório quanto no site do *meetup*, com a diferença de que no meetup após o **sobre os palestrantes** adicionaríamos as infos sobre a talk e o palestrante do evento.

# Sobre o PHPSP Live

O PHPSP Live nasce como uma iniciativa da comunidade para trazer conteúdo online e gratuito, promover interação e estreitar o relacionamento da comunidade no momento em que vivemos a pandemia do COVID-19.

Os eventos **Live** serão no formato de palestras ministradas ao vivo e com duração de 20 à 40 minutos no canal do youtube do [PHPSP](https://www.youtube.com/user/phpsp1).

## Sobre os palestrantes

O PHPSP dará espaço não só a comunidade PHP de São Paulo, a ideia é promovermos interação, união e aprendizado entre a comunidade de forma geral. Os palestrantes serão selecionados entre aqueles que preencherem [este formulário](https://docs.google.com/forms/d/e/1FAIpQLSfT8uZV3uLooNv_FK7qKCqL6b6UPd4qoGVOl_q77TH2kArBRQ/viewform) e não há a necessidade de o palestrante ser de São Paulo e nem necessariamente ser da comunidade PHP. Caso tenham palestras sobre outras linguagens, arquitetura, design de aplicações, agilidade, etc, saibam que este espaço também é de vocês e sintam-se à vontade para submeter palestras!

## Quero palestrar mas nunca palestrei, posso?

O **PHPSP Live** é um evento da comunidade para a comunidade e todos são muito bem-vindos! Basta [submeter sua proposta](https://docs.google.com/forms/d/e/1FAIpQLSfT8uZV3uLooNv_FK7qKCqL6b6UPd4qoGVOl_q77TH2kArBRQ/viewform) e entraremos emc ontato.

Caso tenha interesse em palestrar mas nunca fez algo do gênero conte conosco! Utilize as issues informando o assunto que deseja falar e entraremos em contato para viabilziar sua apresentação! Caso precise de ajuda para estruturar uma palestra, como funciona o formato online, como perder o medo de palestrar, enfim, qualqur coisa, pode contar com a gente que vamos ajudar a viabilizar sua apresentação =)

## Contatos

Não deixe de participar do nosso [canal no slack](https://join.slack.com/t/phpsp/shared_invite/enQtMzI2NjQxNTM4Mzg3LTA4ODU1NWI3ZDYzZWJjZmMzYjczZTc1YTc1ZWUwZjViMTExYzE3MGY3NDljZDYyMTdmNjMxMmM2MTE4ZWJhNmE)! Lá temos um canal para falarmos de eventos além de mais 2000 pessoas conectadas e prontas para ajudar uns aos outros.

**Comment by joelmedeiros** [comment]
Acho legal mencionar no começo aquela parada de "manter o contato" com quem está se sentindo isolado nesse momento de pandemia trabalhando em casa. Algo como: 
> Em meio a essa transição de trabalho no escritório para trabalho forçado em casa muitos podem estar se sentindo sozinhos e estamos fazendo essa iniciativa para ajudar a toda comunidade passar por isso juntos.

**Comment by jpjoao** [comment]
Em cima do que o Joel falou, mas mudando um pouco pois acho que usar "trabalho forçædo" é um pouco pesado e tem uma conotação muito errada. Eu acho bacana a gente se incluir em quem ta impactado pra dar uma ideia de inclusão e não parecer que estamos falando "do alto de nosso pedestal de pessoas imunes para aqueles que sofrem" já que esse nem de longe é o caso.

> Em meio a essa adaptação na transição de trabalho no escritório para a quarentena e o trabalho em casa muitos nós podemos estar nos sentindo um tanto sozinhos e isolado e é justamente para tentar aliviar esses sentimentos que pensamo nessa iniciativa que tenta ajudar toda comunidade nesse tempo dificil e mostrando que podemos sim passar por isso juntos.

**Comment by Morkhusz** [comment]
Adicionei as sugestões numa sessão!
Coloquei o README.md na master, daqui pra frente quem sentir a necessidade de alterações/melhorias basta ir lá e dar um tapa, blz?

Estou fechando a issue aqui
